FROM opensuse:leap
MAINTAINER Rick Ashford <rick.ashford@suse.com>
#RUN zypper -n in -l apache2 unzip
#COPY wordpress.zip /wordpress.zip 
#RUN unzip -d /srv/www/htdocs/ /wordpress.zip
RUN touch /helloworld

CMD tail -f /helloworld
EXPOSE 80
